name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: DinCoder Version
      description: Which version of DinCoder are you using?
      placeholder: e.g., 0.1.15
    validations:
      required: true

  - type: dropdown
    id: ai-agent
    attributes:
      label: AI Agent
      description: Which AI coding assistant are you using?
      options:
        - Claude Code
        - GitHub Copilot
        - Cursor
        - Windsurf
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Output of `node --version`
      placeholder: e.g., v20.11.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What operating system are you using?
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: |
        Example: "When I run constitution_create, it throws an error about missing directory"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Install DinCoder v0.1.15
        2. Run constitution_create with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: |
        Example: "Should create constitution.md in .dincoder/my-project/"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: |
        Example: "Throws error: ENOENT: no such file or directory"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any error messages or logs
      placeholder: |
        Error: ENOENT: no such file or directory, mkdir '/path/to/project'
          at Object.mkdirSync (node:fs:1382:3)
          at constitutionCreate (/path/to/constitution.ts:42:10)
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Share relevant configuration (workspace path, environment variables, etc.)
      placeholder: |
        workspacePath: /Users/me/projects/my-app
        MCP_SERVER_PORT: 3000
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - This started happening after upgrading from v0.1.14
        - Only happens in specific directory structures
        - Workaround: manually create directory first
    validations:
      required: false
